accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register


urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

analysis/urls.py
from django.urls import path
from analysis import views

app_name = 'analysis'

urlpatterns = [
    path('getPic/', views.getPic),
    path('inputImage/', views.inputImage, name='inputImage'),
]

bigday/urls.py
from django.urls import path
from bigday import views

app_name = 'bigday'

urlpatterns = [
    path('', views.home, name='home'),
    path('testView/', views.testView, name='testView'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bigday.urls'), name='bigday'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('analysis/', include('analysis.urls'), name='analysis'),
]

accounts/models.py
from django.db import models

# Create your models here.

analysis/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Label(models.Model):
    id = models.AutoField(primary_key=True)
    label_eng = models.CharField(max_length=50)
    label_kr = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return self.label_eng

bigday/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User


class Child(models.Model):
    chi_num = models.IntegerField(primary_key=True)
    chi_name = models.CharField(max_length=30)
    chi_gen = models.CharField(max_length=10)
    chi_birth = models.CharField(max_length=30)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'child'


class House(models.Model):
    hou_num = models.IntegerField(primary_key=True)
    hou_img = models.ImageField()
    hou_lan = models.TextField()

    class Meta:
        managed = False
        db_table = 'house'


class Person(models.Model):
    per_num = models.IntegerField(primary_key=True)
    per_img = models.ImageField()
    per_lan = models.TextField()

    class Meta:
        managed = False
        db_table = 'person'


class Record(models.Model):
    record_num = models.IntegerField(primary_key=True)
    record_con = models.TextField(blank=True, null=True)
    record_time = models.DateTimeField()
    chi_num = models.ForeignKey(Child, models.DO_NOTHING, db_column='chi_num')
    tree_num = models.ForeignKey('Tree', models.DO_NOTHING, db_column='tree_num')
    hou_num = models.ForeignKey(House, models.DO_NOTHING, db_column='hou_num')
    per_num = models.ForeignKey(Person, models.DO_NOTHING, db_column='per_num')

    class Meta:
        managed = False
        db_table = 'record'


class Tree(models.Model):
    tree_num = models.IntegerField(primary_key=True)
    tree_img = models.ImageField()
    tree_lan = models.TextField()

    class Meta:
        managed = False
        db_table = 'tree'

accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

analysis/forms.py
from django import forms


class InputImage(forms.Form):
    house = forms.ImageField(label='house')
    tree = forms.ImageField(label='tree')
    person = forms.ImageField(label='person')

bigday/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm


def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = RegisterForm()
    return render(request, 'registration/register.html', {'form': user_form})

analysis/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .RCNNTree import getTreeLabel
from .RCNNPerson import getPersonLabel
from .RCNNHouse import getHouseLabel
from time import sleep
import json
from datetime import datetime
from .models import *
from django.shortcuts import get_object_or_404


# Create your views here.
def inputImage(request):
    return render(request, 'analysis/inputImage.html')


num = 1


@csrf_exempt
def getPic(request):
    print("check")
    if request.method == 'POST':
        global num
        hoLo = handle_upload_file(request.FILES['house'], 'house', str(num))
        trLo = handle_upload_file(request.FILES['tree'], 'tree', str(num))
        perLo = handle_upload_file(request.FILES['person'], 'person', str(num))
        # SLEEP 1초(파일 저장시간)
        sleep(1)
        # 분석 모델 시작
        result1 = getHouseLabel(str(num))
        result2 = getTreeLabel(str(num))
        result3 = getPersonLabel(str(num))
        houseHtml = getLabelHTP(result1)
        treeHtml = getLabelHTP(result2)
        personHtml = getLabelHTP(result3)
        imgHouse = "<div style=\"display:block; margin: auto;\" class=\"col-md-4\">" \
                   "<img style=\"width: 20rem; height: 20rem;\" src=\"../../static/labelImage/houseLabel" + str(num) + ".jpg\">" \
                   "</div>" \
                   "<br>" + houseHtml
        imgTree = "<div style=\"display:block; margin: auto;\" class=\"col-md-4\">" \
                  "<img style=\"width: 20rem; height: 20rem;\" src=\"../../static/labelImage/treeLabel" + str(num) + ".jpg\">" \
                   "</div><br>" + treeHtml
        imgPerson = "<div style=\"display:block; margin: auto;\" class=\"col-md-4\">" \
                    "<img style=\"width: 20rem; height: 20rem;\" src=\"../../static/labelImage/personLabel" + str(num) + ".jpg\">" \
                   "</div><br>" + personHtml
        context = {'imgHouse': imgHouse, 'imgTree': imgTree, 'imgPerson': imgPerson, }
        num += 1
        return HttpResponse(json.dumps(context), "application/json")


def getLabelHTP(labelname):
    dnum = 0
    result = "<div style=\"display:block;\" class=\"col-md-8\">" \
             "<h3 style=\"text-align: left;\"><strong>그림 해석</strong></h3>" \
             "<ul style=\"line-height: 200%; text-align: justify; font-size: larger;\">"
    label = list(set(labelname['class']))

    for _ in label:
        labelEng = label[dnum]
        data = get_object_or_404(Label, label_eng=labelEng)
        labelContent = data.content
        result += "<li>" + labelContent + "</li>"
        dnum += 1

    result += "</ul></div>"
    return result


def handle_upload_file(f, name, count):
    fileLocation = './media/photos/' + name + '/' + name + count + '.jpg'
    with open(fileLocation, 'wb+') as destination:
        destination.write(f.read())
    return fileLocation

bigday/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'bigday/home.html')


def testView(request):
    return render(request, 'bigday/testView.html')

analysis/templates/analysis/inputImage.html
{% extends 'base.html' %}
{% block title %}- start Test{% endblock %}

{% block content %}
  <section style="font-family: 'Gaegu', cursive;" id="projects" class="about-section text-center">
      <div style="margin-top: 0;" class="testView">
        <h1><strong>그림 업로드</strong></h1>
          <div>
              <div style="display: block;">
                <div class="uploadPhoto">
                    <div style="margin: 0 !important;">
                        <form name="inputImg" method="POST">
                            <div style="display: flex;" class="container">
                                <div style="display: block;" class="col-md-4">
                                    <h3><strong>집</strong></h3>
                                    <div style="margin-bottom: 1rem;" class="custom-file">
                                        <input previewnum="foo1" type="file" class="custom-file-input" id="imgInp1" name="imgInp1">
                                        <label class="custom-file-label" for="imgInp1">Choose file</label>
                                    </div>
                                    <img style="width: 20rem; height: 20rem;" id="foo1"/>
                                </div>

                                <div style="display: block;" class="col-md-4">
                                    <h3><strong>나무</strong></h3>
                                    <div style="margin-bottom: 1rem;" class="custom-file">
                                        <input previewnum="foo2" type="file" class="custom-file-input" id="imgInp2" name="imgInp2">
                                        <label class="custom-file-label" for="imgInp2">Choose file</label>
                                    </div>
                                    <img style="width: 20rem; height: 20rem;" id="foo2"/>
                                </div>

                                <div style="display: block;" class="col-md-4">
                                    <h3><strong>사람</strong></h3>
                                    <div style="margin-bottom: 1rem;" class="custom-file">
                                        <input previewnum="foo3" type="file" class="custom-file-input" id="imgInp3" name="imgInp3">
                                        <label class="custom-file-label" for="imgInp3">Choose file</label>
                                    </div>
                                    <img style="width: 20rem; height: 20rem;" id="foo3"/>
                                </div>
                            </div>
                            <br>
                            {% csrf_token %}
                            <input class="btn btn-info" style="background-color:#494d4e; border-color:#494d4e;" id="picSend" type="submit" value="등록">
                            <div id="resultView">
                                <h3 id="resultTxt"></h3>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
          </div>
      </div>
      <div style="display: none; font-family: 'Gaegu', cursive;" id="username">
          <h1><strong>{{user.get_username}}</strong>님의 분석 결과입니다.</h1>
          <br>
      </div>
      <div style="display: none; font-family: 'Gaegu', cursive;" id="resultImg" class="container">
          <br>
          <div style="display: flex; justify-content: center; padding: 3rem; background: #dc354514;" id="resultImg1"></div>
          <br>
          <br>
          <br>
          <div style="display: flex; justify-content: center; padding: 3rem; background: #dc354514;" id="resultImg2"></div>
          <br>
          <br>
          <br>
          <div style="display: flex; justify-content: center; padding: 3rem; background: #dc354514;" id="resultImg3"></div>
      </div>

  </section>


<script src="http://code.jquery.com/jquery-latest.js"></script>
<script>
     // using jQuery
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $(document).ready(function() {
        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
          }
        });
      });
</script>
<script type="text/javascript">
    function readURL(input, previewnum) {
        previewnum = "#"+previewnum;
          var reader = new FileReader();
          reader.onload = function(e) {
              $(previewnum).attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
    }

  $(".custom-file-input").change(function() {
       var previewnum = $(this).attr('previewnum');
      readURL(this, previewnum)
  });
</script>
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.ajax-cross-origin.min.js' %}"></script>
<script>
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
<script>
$('#picSend').on("click",function() {
    imgForm = document.inputImg;
    if (imgForm.imgInp1.value==""||imgForm.imgInp2.value==""||imgForm.imgInp3.value==""){
        alert("사진을 모두 입력해주세요.");
        return imgForm.imgInp1.focus();
        /*swal({
            title: "사진을 모두 입력해주세요",
            icon: "warning",
          }).then(result => {
              continue;
        })*/
    }

    var formData = new FormData();
    formData.append("house", $("#imgInp1")[0].files[0]);
    formData.append("tree", $("#imgInp2")[0].files[0]);
    formData.append("person", $("#imgInp3")[0].files[0]);
        $.ajax({
            crossOrigin : true,
            url: '/analysis/getPic/',
            type: 'POST',
            dataType:'json',
            processData: false,
            contentType: false,
            data : formData,
            success: function (result) {
                document.getElementById("resultImg").style.display="block";
                document.getElementById("username").style.display="block";
                $("#resultTxt").remove();
                $("#resultImg1").append(result['imgHouse']);
                $("#resultImg2").append(result['imgTree']);
                $("#resultImg3").append(result['imgPerson']);
            }
        });
        $("#picSend").remove();
        $("#resultTxt").append("데이터 분석중입니다...");
})
</script>
{% endblock %}

bigday/templates/bigday/home.html
{% extends 'base.html' %}

{% block title %}- Home{% endblock %}

{% block content %}

  <!-- main -->
  <section style="font-family: 'Gaegu', cursive !important;" class="masthead">
    <div style="display:flex; justify-content: space-around;" class="container d-flex h-100 align-items-center">
      <div style="margin: 0px !important; display:block;" class="mx-auto text-center">
        <h2 style="text-align: center; margin: 0px 0px 20px!important; color: black !important; font-size: xx-large;" class="text-white-50 mx-auto mt-2 mb-5">아이들의 마음이, <strong>다</strong> 다르다.</h2>
        {% load static %}
        <img style="display: block; width: 300px; height: 300px; margin: 50px;" src="{% static 'image/crayons.png' %}">
        <h2 style="text-align: center; margin: 20px 0px !important; color: black !important; font-size: xx-large;" class="text-white-50 mx-auto mt-2 mb-5">아이들의 마음에, <strong>다다르다</strong>.</h2>
        <a style="margin-top: 20px;" href="{% url 'bigday:testView' %}" class="btn btn-primary js-scroll-trigger">Get Started</a>
      </div>

    </div>
  </section>

  <!-- About Section -->
  <section style="font-family: 'JejuMyeongjo' !important;" id="about" class="projects-section bg-light">
    <div class="container">
        <p style="text-align: center; font-size: -webkit-xxx-large;">인사말</p>
        <br>
        <p style="text-align: justify; font-size: larger; margin: 0 3rem; line-height: 200%;">
            안녕하세요,<br>
            아동그림을 바탕으로 심리 상담 서비스를 제공하고 있는 <strong>마음이</strong> 입니다.<br>
            마음이는 한국 아동의 심리적 스트레스가 지속해서 증가하고 있을 뿐만 아니라, OECD 국가 중 학업 스트레스가 가장 높다는 것을 확인할 수 있었습니다.<br>
            이에 많은 아이들이 스트레스 관리가 필요로 하며, 부모의 관심과 보호가 필요한 상태임을 파악할 수 있었습니다. 해당 자료를 근거로 아동에 특화된 온라인 검사 서비스를 제공하여 이미지 인식 기반 검사 서비스를 무료로 제공 중에 있습니다.<br>
            어린이들의 그림은 어린이 자신만의 마음 세계를 때 묻지 않은 감정의 상태와 순수하고 솔직하게 표현해 내는 그림으로 주관의 세계를 형상화하는 것이라고 볼 수 있습니다. 이에 그림을 그리고자 하는 욕구와 창조하고자 하는 욕구가 어린이들에게 나타나는 바, 이런 욕구의 하나로 표출되는 것이 그림을 그리고자 하는 욕구입니다. 이를 활용해 마음속에 내재된 욕구나 갈등을 해소시켜 주고 정서적으로 안정을 줄 수 있는 서비스를 지속해서 제공해나가겠습니다.<br>
            감사합니다.<br>
        </p>
        <p style="text-align: end; font-size: larger; margin: 0 3rem;">
            <strong>마음이 드림</strong>.
        </p>
    </div>
  </section>

  <section style="font-family: 'JejuMyeongjo' !important;" id="htpTest" class="about-section text-center">
    <div class="container">
        <p style="text-align: center; font-size: -webkit-xxx-large;">HTP 검사</p>
        <p style="text-align: justify; font-size: initial; margin: 0 3rem; line-height: 200%;">
            HTP그림검사는 집, 나무, 사람을 그리게 하여 심리상태를 직관적으로 파악할 수 있는 검사입니다.<br>
            <strong>첫번째</strong>, 연령이 낮은 아동들에게도 익숙하며
            <strong>둘째</strong>, 비교적 모든 연령층의 피검자의 호의적으로 받아들인다고 생각할 수 있으며,
            <strong>셋째</strong> 솔직하고 자유로운 언어적 표현을 이끌어낼 수 있는 요소들이라고 생각해서입니다.<br>
            이에 각 그림들이 투사하는 요인은 아래와 같습니다.</p>
        <br>
      <ul style="text-align: justify; font-size: larger; margin: 0 3rem; line-height: 200%;">
          <li><strong>H (House - 집 그림)</strong><br>
              성장해온 가정상황, 가정생활, 가족관계, 감정, 이상적인 미래의 가정에 대한 소망, 심리적 적응, 현실과의 접근, 외부세계와의 접촉 가능성을 볼 수 있습니다.</li>
          <li><strong>T(Tree - 나무 그림)</strong><br>
              자기상, 현재 자신의 마음상태를 무의식적으로 느끼고 있는 상태를 반영하며 가지고 있는 에너지, 성장기에 겪은 정서적 충격의 정도, 정신적인 성숙정도를 볼 수 있습니다.</li>
          <li><strong>P(Person - 사람 그림)</strong><br>
              사람에 대한 인식상태, 자기상, 성격, 왜곡, 소통중의 방어기재, 신경증 등을 살필 수 있습니다. 심리적인 공포감, 불안감, 정서 상태가 보이기도 하며 지능수준, 현실감, 자기통제력, 대인에 대한 관심도를 알 수 있습니다.</li>
      </ul>
    </div>
  </section>

  {% endblock %}

bigday/templates/bigday/testView.html
{% extends 'base.html' %}

{% block title %}- HTP Test{% endblock %}

{% block content %}

  <section style="font-family: 'JejuMyeongjo' !important;" id="projects" class="about-section text-center">
      <div style="margin-top: 0;" class="testView">
          <br>
          <p style="font-size: xx-large;"><strong>그림 그리는 방법</strong></p>
          <br>
          <div style="display: inline-block;">
              <ol style="text-align: justify; line-height: 250%;">
                  <li>먼저 A4 용지 한 장과 연필, 지우개를 아이 앞에 놓아 주세요.</li>
                  <li>첫 번째 용지에는 집을 그릴 수 있도록 지도해주세요.</li>
                  <li>집을 그린 후에 추가로 더 그려 넣고 싶은 것이 있다면 그릴 수 있도록 안내해주세요.</li>
                  <li>다 그린 아이들을 위해 새로운 용지를 준비해주세요.</li>
                  <li>두 번째 용지에는 나무를 그릴 수 있도록 지도해주세요.</li>
                  <li>나무를 그린 후에 추가로 그려 넣고 싶은 것이 있으면 그릴 수 있도록 안내해주세요.</li>
                  <li>다 그린 아이들을 위해 새로운 용지를 준비해주세요.</li>
                  <li>이번에는 용지를 세로로 놔주세요.</li>
                  <li>용지에 사람을 그리는데 막대 사람을 그리지 마시고, 잘 그려야 하지는 않지만 최대한 정성껏 그릴 수 있도록 아이들을 지도해주세요.</li>
                  <li>다 그린 경우, 그림을 스캔한 후에 집, 사람, 나무를 순서대로 업로드해주세요.</li>
              </ol>
          <br>
          <br>
          </div>
      </div>
      <div style="display: block; text-align: center;">
          <div style="display: inline-block;">
              <p style="font-size: xx-large;"><strong>유의사항</strong></p>
              <br>
                  <ul style="text-align: justify; line-height: 250%;">
                      <li>검사 결과는 검사 당시의 주변 상황에 따라 민감하게 달라질 수 있으므로 주변을 정리한 후에 진행해주세요.</li>
                      <li>책상 정리를 해 주시고 검사 중 불필요한 행동이나 잡담을 삼가도록 안내 부탁 드립니다.</li>
                      <li>솔직하고 성실하게 실시 할 수 있도록 지도해주세요.</li>
                  </ul>
          </div>
      </div>
      <br>
      <br>
      <a style="font-family: 'JejuMyeongjo';" class="btn btn-primary" href="{% url 'analysis:inputImage' %}">그림 등록하기</a>
  </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Maeum {% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  {% load static %}
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-168774278-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-168774278-1');
  </script>




  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static 'grayscale.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'style.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Gaegu&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:600" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

  <style>
    @font-face {
        font-family: 'JejuMyeongjo';
        font-style: normal;
        font-weight: 400;
        src: url(//fonts.gstatic.com/ea/jejumyeongjo/v3/JejuMyeongjo-Regular.eot);
        src: url(//fonts.gstatic.com/ea/jejumyeongjo/v3/JejuMyeongjo-Regular.eot?#iefix) format('embedded-opentype'),
             url(//fonts.gstatic.com/ea/jejumyeongjo/v3/JejuMyeongjo-Regular.woff2) format('woff2'),
             url(//fonts.gstatic.com/ea/jejumyeongjo/v3/JejuMyeongjo-Regular.woff) format('woff'),
             url(//fonts.gstatic.com/ea/jejumyeongjo/v3/JejuMyeongjo-Regular.ttf) format('truetype');
      }

    @font-face {
        font-family: 'SeoulHangangM';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulHangangM.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

    @font-face {
        font-family: 'TDTDTadakTadak';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.0/TDTDTadakTadak.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
  </style>

</head>

<body id="page-top">

  <!-- Navigation -->
  <haeder>
      <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div style="font-family: 'Gaegu', cursive !important;" class="container">
          <a style="font-size: -webkit-xxx-large;" class="navbar-brand js-scroll-trigger" href="{% url 'bigday:home' %}#page-top">마음이</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                {% if user.is_authenticated %}
                <li class="nav-item">
                <a style="font-size: large; color:black;">{{user.get_username}}님 반갑습니다.</a>
              </li>
                <li class="nav-item">
                  <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'logout' %}">logout</a>
                </li>

                {% else %}
                <li class="nav-item">
                  <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'login' %}">login</a>
                </li>
                <li class="nav-item">
                  <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'register' %}">signup</a>
                </li>

                {% endif %}
              <li class="nav-item">
                <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'bigday:home' %}#about">마음이소개</a>
              </li>
              <li class="nav-item">
                <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'bigday:home' %}#htpTest">HTP 검사 </a>
              </li>
              <li class="nav-item">
                <a style="font-size: x-large; padding: 0 1.5rem;" class="nav-link js-scroll-trigger" href="{% url 'bigday:testView' %}">그림상담 </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  </haeder>
  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer style="padding:4rem 0;" class="bg-black small text-center text-white-50">
      <section class="contact-section bg-black">
      <div class="container">
          <div class="social d-flex justify-content-center">
            <a href="#" class="mx-2">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#" class="mx-2">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#" class="mx-2">
              <i class="fab fa-github"></i>
            </a>
          </div>
          <p style="margin: 1rem 0; color: black;">Copyright &copy; Maeum-I 2019</p>
      </div>
      </section>
  </footer>

  <!-- Bootstrap core JavaScript -->
{% load static %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/grayscale.min.js' %}"></script>


  <script type="text/javascript">
    $(document).ready(function() {
          /*
          var defaults = {
          containerID: 'toTop', // fading element id
          containerHoverID: 'toTopHover', // fading element hover id
          scrollSpeed: 1200,
          easingType: 'linear'
          };
          */
    $().UItoTop({ easingType: 'easeOutQuart' });
    });
  </script>


</body>

</html>